---
output: pdf_document
header-includes: 
  - \usepackage[utf8]{inputenc}
  - \usepackage{graphicx}
  - \usepackage{caption}
  - \usepackage[margin=1in]{geometry}
  - \usepackage{amsmath,amssymb}
  - \usepackage{multicol}
  - \usepackage{array}
  - \usepackage{tabulary}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newcommand{\class}{EC 370}
\newcommand{\term}{Xiang LI (GE)}
\newcommand{\examnum}{Chapter 14 - part 1 - Practice}

\noindent
\begin{tabular*}{\textwidth}{l @{\extracolsep{\fill}} r @{\extracolsep{6pt}} l}
\textbf{\class} & \textbf{Name: } & \makebox[2in]{\hrulefill}\\
\textbf{\term} &&\\
\textbf{\examnum} & \textbf{UO ID: } & \makebox[2in]{\hrulefill}\\
\end{tabular*}
\rule[2ex]{\textwidth}{2pt}



\textbf{QUESTION 1} 

"The Fed can perfectly control the amount of borrowed reserves in the banking system." Is this statement true, false, or uncertain?




\vspace{.5in}
\textbf{QUESTION 2} 

If First National Bank \textbf{pays off} a \$2 million loan to the Fed, show the changes in the balance sheet of the Fed and the First National Bank. 

\begin{center}
\begin{tabular}{|p{6cm}|p{6cm}|} 
\hline
\multicolumn{2} {|c|} {\textbf{First National Bank}} \\
\hline
\textbf{Assets} & \textbf{Liabilities+Capital} \\ 
\hline\hline
Reserves:  & Deposits:  \\ 
\hline
Securities: &  Borrowings:  \\
 \hline
 Loans:  & Capital:   \\
 \hline\hline\hline
 \multicolumn{2} {|c|} {\textbf{Federal Reserve System}} \\
 \hline
\textbf{Assets} & \textbf{Liabilities} \\ 
\hline\hline
Securities: &Currency in circulation:  \\ 
\hline
Lending to banks:  &  Reserves:  \\
\hline
\end{tabular}
\end{center} 





\vspace{.3in}
\textbf{QUESTION 3} 

If the Fed sells \$2 million of bonds to the First National Bank, what happens to reserves and the monetary base? Use balance sheet to explain your answer. 

\begin{center}
\begin{tabular}{|p{6cm}|p{6cm}|} 
\hline
\multicolumn{2} {|c|} {\textbf{First National Bank}} \\
\hline
\textbf{Assets} & \textbf{Liabilities+Capital} \\ 
\hline\hline
Reserves:    & Deposits:  \\ 
\hline
Securities:  &  Borrowings:  \\
 \hline
 Loans:  & Capital:   \\
 \hline\hline\hline
 \multicolumn{2} {|c|} {\textbf{Federal Reserve System}} \\
 \hline
\textbf{Assets} & \textbf{Liabilities} \\ 
\hline\hline
Securities:    &Currency in circulation:  \\ 
\hline
Lending to banks:  &  Reserves:   \\
\hline
\end{tabular}
\end{center} 

\newpage

\vspace{.3in}
\textbf{QUESTION 4} 

Suppose that depositors wants to convert more currency into checkable deposits at the First National Bank. Use balance sheet of the Fed and the First National Bank to show the changes in each of the items, after there is a \$10 million shifting from currency to deposits. 

\begin{center}
\begin{tabular}{|p{6cm}|p{6cm}|} 
\hline
\multicolumn{2} {|c|} {\textbf{First National Bank}} \\
\hline
\textbf{Assets} & \textbf{Liabilities+Capital} \\ 
\hline\hline
Reserves:     & Deposits: \\ 
\hline
Securities:  &  Borrowings:  \\
 \hline
 Loans:  & Capital:   \\
 \hline\hline\hline
 \multicolumn{2} {|c|} {\textbf{Federal Reserve System}} \\
 \hline
\textbf{Assets} & \textbf{Liabilities} \\ 
\hline\hline
Securities:   &Currency in circulation:  \\ 
\hline
Lending to banks:  &  Reserves:  \\
\hline
\end{tabular}
\end{center} 




\vspace{.3in}
\textbf{QUESTION 5} 

The required reserve ratio on checkable deposits is 10\%.

(1) If the Fed lends First National Bank a total of \$100 million, update the balance sheet. 

\begin{center}
\begin{tabular}{|p{6cm}|p{6cm}|} 
\hline
\multicolumn{2} {|c|} {\textbf{First National Bank}} \\
\hline
\textbf{Assets} & \textbf{Liabilities+Capital} \\ 
\hline\hline
Reserves:     & Deposits:  \\ 
\hline
Securities: &  Borrowings:   \\
 \hline
 Loans:  & Capital:   \\
 \hline\hline\hline
 \multicolumn{2} {|c|} {\textbf{Federal Reserve System}} \\
 \hline
\textbf{Assets} & \textbf{Liabilities} \\ 
\hline\hline
Securities:    &Currency in circulation:  \\ 
\hline
Lending to banks:   &  Reserves:    \\
\hline
\end{tabular}
\end{center} 

(2) If the Fed lends First National Bank a total of \$100 million, and suppose depositors withdraw \$50 million and hold it as currency. Update the balance sheet.

\begin{center}
\begin{tabular}{|p{6cm}|p{6cm}|} 
\hline
\multicolumn{2} {|c|} {\textbf{First National Bank}} \\
\hline
\textbf{Assets} & \textbf{Liabilities+Capital} \\ 
\hline\hline
Reserves:     & Deposits:  \\ 
\hline
Securities: &  Borrowings: \\
 \hline
 Loans:  & Capital:   \\
 \hline\hline\hline
 \multicolumn{2} {|c|} {\textbf{Federal Reserve System}} \\
 \hline
\textbf{Assets} & \textbf{Liabilities} \\ 
\hline\hline
Securities:    &Currency in circulation:  \\ 
\hline
Lending to banks:   &  Reserves:    \\
\hline
\end{tabular}
\end{center} 







