---
output: pdf_document
header-includes: 
  - \usepackage[utf8]{inputenc}
  - \usepackage{graphicx}
  - \usepackage{caption}
  - \usepackage[margin=1in]{geometry}
  - \usepackage{amsmath,amssymb}
  - \usepackage{multicol}
  - \usepackage{array}
  - \usepackage{tabulary}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newcommand{\class}{EC 370}
\newcommand{\term}{Xiang LI (GE)}
\newcommand{\examnum}{Participation 1 (Chapter 1)}

\noindent
\begin{tabular*}{\textwidth}{l @{\extracolsep{\fill}} r @{\extracolsep{6pt}} l}
\textbf{\class} & \textbf{Name: } & \makebox[2in]{\hrulefill}\\
\textbf{\term} &&\\
\textbf{\examnum} & \textbf{UO ID: } & \makebox[2in]{\hrulefill}\\
\end{tabular*}
\rule[2ex]{\textwidth}{2pt}

Answer the following questions. Write legibly, take a high quality scan of your responses, compile all pages into one pdf, and upload only one pdf document to Canvas by **11:59pm, PDT, Sunday, April 5**. 

\vspace{.5in}

\textbf{QUESTION 1} 

If real GDP grew from \$9 trillion in 2019 to \$9.5 trillion in 2020, then the GDP growth rate for 2020 would be?

\vspace{2in}

\textbf{QUESTION 2} 

If the cost of the basket rises from \$500 to \$600, CPI has risen by? 

\vspace{2in}

\textbf{QUESTION 3} 

If the GDP deflator rose from 111 in 2019 to 113 in 2020, the inflation rate using the GDP deflator would be?


