---
output: pdf_document
header-includes: 
  - \usepackage[utf8]{inputenc}
  - \usepackage{graphicx}
  - \usepackage{caption}
  - \usepackage[margin=1in]{geometry}
  - \usepackage{amsmath,amssymb}
  - \usepackage{multicol}
  - \usepackage{array}
  - \usepackage{tabulary}
  - \usepackage{xcolor}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newcommand{\class}{EC 370}
\newcommand{\term}{Xiang LI (GE)}
\newcommand{\examnum}{Final - Review Guide}

\noindent
\begin{tabular*}{\textwidth}{l @{\extracolsep{\fill}} r @{\extracolsep{6pt}} l}
\textbf{\class} & \textbf{Name: } & \makebox[2in]{\hrulefill}\\
\textbf{\term} &&\\
\textbf{\examnum} & \textbf{UO ID: } & \makebox[2in]{\hrulefill}\\
\end{tabular*}
\rule[2ex]{\textwidth}{2pt}



This guide is intended to give you a broad overview of the topics covered so far in the course to help you prepare for the midterm exam. The items listed are not necessarily an exhaustive list of the vocabulary or ideas discussed, but understanding these topics thoroughly will provide you with a good basis for success on the final exam.

**Chapter 1, 2, 3 will not be covered in the final exam. Content in \textcolor{blue}{blue} are materials covered in Midterm #1 and Midterm #2. The final exam will be more heavily weighted toward the materials discussed after Midterm #2.**



<!---
\noindent

- Time and location of Final exam: \textbf{10:15-12:15, Friday, Dec 13, at 240A MCK}.

- I will hold extra office hours before the exam: \textbf{10:15-12:15pm, Thursday, Dec 12, at PLC 407.} 

- Total score for final exam is 120 points, consisting of the following questions: 
	
- Chapter 1, 2, 3 are NOT tested in the final exam.

- Take full advantage of lecture slides, practice problem sets, 2 midterms, 5 problem sets to prepare for the final exam. 

- Feel free to email me if you have any questions: xli4@uoregon.edu
--->

# Chapter 19

## Quantity theory of money
- equation of exchange
- quantity theory of money and inflation
- government budge constraint and inflation


## Keyesian liquidity preference theory of money demand
- 3 motives
- equation of real money demand
  - relationship between demand for real money and interest rate
  - relationship between demand for real money and income
  - why velocity is not a constant


# Chapter 15

## The Market for Reserves and the Federal Funds Rate
- demand curve for reserves, supply curve for reserves, market equilibrium, excess supply, excess demand



## Changes in the Federal Funds Rate
- open market operation
  - if supply curve initially intersects demand curve on the downward-sloped section
  - if supply curve initially intersects demand curve on the flat section
  - Advantages of Open market operations
- discount policy
  - if demand curve initially intersects supply curve on the vertical section
  - if demand curve initially intersects supply curve on the flat section
- reserve requirement
- interest paid on reserves
  - if supply curve initially intersects demand curve on the downward-sloped section
  - if supply curve initially intersects demand curve on the flat section
- How the Fed Limit Fluctuations in the Fed Funds Rate


## Nonconventional Monetary Policy Tools
- why conventional monetary policy tools fail as occurred in the Great Recession: zero-lower-bound problem
- liquidity provision
  - discount window expansion: to lower discount rate 
  - term auction facility: loans rate are lower than discount rate, and are set competitively via auction 
  - new lending program: the Fed lends to investment banks
- large-scale asset purchases
  - QE1: purchase of mortgage-backed securities; to lower interest rates on residential mortgages 
  - QE2: purchase of long-term Treasury securities; to lower long-term interest rates 
  - QE3: combining QE1 and QE2
  - weakness of QE
- negative interest rates on bank deposits at a central bank: 
  - banks pay their central bank to keep deposits in the central bank; to encourage banks to lend out the deposits they are keeping at the central bank 
  - weakness of this tool
- Forward guidance: the Fed committing to the future policy action of
keeping the federal funds rate at zero for an extended period



# Chapter 14
## Three Players in the Money Supply Process
- central bank: conduct monetary policy by changing its holdings of assets and liabilities 
- banks: accept deposits from individuals and institutions and make loans 
- depositors (individuals and institutions): hold deposits in banks  

## the Fed's Balance Sheet
- Liabilities (Monetary Base): $MB=C+R$
  - currency in circulation (C): currency held by nonbank public
  - reserves (R): bank deposits at the Fed + vault cash held by banks
- Assets
  - securities issued by the U.S. Treasury
  - loans to banks/discount loan/borrowings from the Fed
  
## 2 Ways for the Fed to Control Monetary Base
- open market operation: use T-account to analyze how this changes monetary base 
- discount loan: use T-account to analyze how this changes monetary base 
- $MB=MB_n + BR$  
- understand why shifts from deposits to currency does not change MB

## Simple Deposit Multiplier
- understand how a \$100 million increase in reserves leads to a $\frac{1}{rr} \times 100$ million increase in deposits, a $\frac{1}{rr} \times 100$ million increase in loans, and a $100$ million increase in reserves
- critiques of simple deposit multiplier 

## Money Multiplier
- 5 factors that determine the money supply 
- understand how a \$100 million increase in monetary base leads to a $\frac{1+c}{c+rr+er} \times 100$ million increase in money supply 
- Application:  2007-2017, why the growth rate of money supply is less than that of monetary base


# Chapter 9

## General Principles of Bank Management

- Liquidity Management
  - T-account example: sufficient excess reserve
  - T-account example: insufficient excess reserve and 4 options
- Capital Adequacy Management 
  - T-account example: how adequate capital can prevent insolvency


\color{blue}

## Basic Banking
- Asset transformation: borrow short and lend long
- Three T-account examples on the slide
  
## Bank Balance Sheet

- Liabilities
  - checkable deposits
  - (primary liabilities) non-transaction deposits 
  - borrowings: discount loans, federal funds
- Assets
  - reserves: required reserves (required reserve ration times checkable deposits), excess reserves
  - securities: U.S. government (secondary reserves), state and local government securities
  - (primary assets) loans: the highest interest rate, the highest default risk, the least liquidity 
- Bank Capital = assets - liabilities 

  
  
# Chapter 6

## Risk structure of interest rates
- graphically explain bonds with default risk have higher interest rates
	- corporate bonds vs. U.S Treasury bonds
	- bonds issued by foreign government that has default risk vs.  U.S Treasury bonds
	- corporate bonds with A rating vs. corporate bonds with B/C rating 
-  graphically explain why bonds with less liquidity have higher interest rates
	- corporate bonds vs. U.S Treasury bonds
-  graphically explain bonds with favorable tax treatment has lower interest rates
	- municipal bonds vs. U.S Treasury bonds


## Term structure of interest rates
- 3 important facts about yield curve
	- fact 1: interest rates on bonds of different maturities move together over time
	- fact 2: When short-term interest rates are low, yield curves are more likely to have an upward slope; when short-term interest rates are high, yield curves are more likely to slope downward
	- act 3: Yield curves almost always slope upward
- expectations theory
	- what is key assumption
	- formula: the n-period interest rate equals the average of the one-period interest rates expected to occur over the n-period life of the bond
	- why this theory can explain Fact 1 and Fact 2
- Segmented Markets Theory
	- what is key assumption
	- demand for long-term bonds is typically lower than that for short-term bonds
	- why this theory can explain Fact 3
- Liquidity Premium Theory
	- what is key assumption
	- formula: the n-period interest rate equals the average of the one-period interest rates expected to occur over the n-period life of the bond plus liquidity premium
	-  liquidity premium grows with the term to maturity 
	- why this theory can explain Fact 1, 2, 3



# Chapter 5

## Demand and Supply in the Bond Market
- what does demand curve for bond look like 
	- negative relationship between bonds price and bonds demand
	- negative relationship between bonds price and interest rate
- what does supply curve for bond look like
- bond market equilibrium, excess demand, excess supply
	- excess demand: P will rise, i will fall
	- excess supply: P will fall, i will rise


## Shift of Demand and Supply in the Bond Market
- Changes in factors that affect how many bonds people will want to hold will make demand curve for bonds shift
	- wealth: 
		- business cycle expansion/recession
		- propensity to save
	- Expected returns on bonds relative to alternative assets
		- expected future interest rates
		- Expected return on alternative assets
		- Expected inflation
	- Risk of bonds relative to alternative assets
	- Liquidity of bonds relative to alternative assets
- Changes in factors that affect how much of an asset corporates or government will want to issue will make supply curve shift
	- Expected profitability of investment opportunities
		- business cycle expansion/recession
	- Expected inflation
	- Government budget deficits




## Bond Market Framework and Liquidity Preference Framework
- what is the key assumption 
- relationship between bond market and market for money
  - if $B^s=B^d$, then $M^s=M^d$
  - if $B^s>B^d$, then $M^s<M^d$
  - if $B^s<B^d$, then $M^s>M^d$


## Demand and Supply in the Market for Money
- what does demand curve for money look like 
	- price of money: interest rate
	- negative relationship between interest rate and demand for money
- what does supply curve for money look like
- bond market equilibrium, excess demand, excess supply
	- excess demand: i will rise
	- excess supply: i will fall


## Shift of Demand and Supply in the Market for Money
- 2 factors cause the demand curve for money to shift
  - income: business cycle expansion/recession
  - price level: business cycle expansion/recession
- increase/decrease in the money supply engineered by the Fed shifts the supply curve







# Chapter 4
## Valuing Monetary Payments Now and in the Future
- how to calculate future value of payments made today
- how to calculate present value of payments made in the future  


## Yield to Maturity
- Yield to Maturity (YTM): the interest rate that equates the present value of all of its future cash flow payments received from an instrument with its value today (today's price)
- how to calculate YTM for:
	- Simple loan
	- Fixed-payment loan
	- Coupon bond
	- Discount Bond (Zero-Coupon bond)
- an important relationship about YTM and coupon rate $c$: 
	- when bond price = bond face value, YTM = $c$ 
	- when bond price < bond face value, YTM > $c$
	- when bond price > bond face value, YTM < $c$
- bond prices and YTM (interest rate) are negatively related



## Holding Period Return (or Return, Rate of Return)
- difference between Yield to Maturity and Rate of Return
- how to calculate one-year holding period rate of return $R$:
	- flexibly make full use of $C(=c \times F)$, $P_t$, $P_{t+1}$,$i_c$, $g$ to calculate $R$
	- how to calculate $P_t$: 
		-  $P_t$ equals: time t's value of all future payments
		-  $P_t$ = face value: if $i_t=c$ (i.e. if $YTM_t=c$ )
		-  $P_t$ can be calculated by $g=\frac{P_{t+1}-P_t}{P_t}$, if $g$ and $P_{t+1}$ are known
		-  $P_t$ can be calculated by $i_c=\frac{C}{P_t}$, if $C(=c \times F)$ and $i_c$ are known
	- how to calculate $P_{t+1}$:
		-  $P_{t+1}$ equals: time t+1's value of all future payments
		-  $P_{t+1}$ = face value: if $i_{t+1}=c$ (i.e. if $YTM_{t+1}=c$ )
		-  $P_{t+1}$ can be calculated by $g=\frac{P_{t+1}-P_t}{P_t}$ if $g$ and $P_t$ are known;
	- an important relationship about current yield $i_c (= \frac{c \times F}{P_t})$ and coupon rate $c$:
		- when $P_t=F, i_c=c$
		- when $P_t>F, i_c<c$
		- when $P_t<F, i_c>c$



## Interest-Rate Risk
- after you have purchased a bond, if there is going to be a rise (fall) in interest rate, then it means that the price of the bond you are holding will fall (increase) and experience a capital loss (gain); if the loss (gain) is large enough, the bond you are holding can be a poor (good) investment
- Prices and returns for long-term bonds are more volatile than those for shorter-term bonds. In other words, long-term bonds have substantial interest-rate risk, compared to short-term bonds


## Real and Nominal Interest Rates
- difference between Real and Nominal Interest Rates
- how to use Fisher equation to calculate real interest rate
- When the real interest rate is low, there are greater incentives to borrow and fewer incentives to lend

