---
output: pdf_document
header-includes: 
  - \usepackage[utf8]{inputenc}
  - \usepackage{graphicx}
  - \usepackage{caption}
  - \usepackage[margin=1in]{geometry}
  - \usepackage{amsmath,amssymb}
  - \usepackage{multicol}
  - \usepackage{array}
  - \usepackage{tabulary}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newcommand{\class}{EC 313, Fall 2019}
\newcommand{\term}{Xiang LI (GE)}
\newcommand{\examnum}{Midterm 2 - Equation Sheet}

\noindent
\begin{tabular*}{\textwidth}{l @{\extracolsep{\fill}} r @{\extracolsep{6pt}} l}
\textbf{\class} & \textbf{Name: } & \makebox[2in]{\hrulefill}\\
\textbf{\term} &&\\
\textbf{\examnum} & \textbf{UO ID: } & \makebox[2in]{\hrulefill}\\
\end{tabular*}
\rule[2ex]{\textwidth}{2pt}

\textit{Work on this page will not be graded. You can detach this page.}


\vspace{.5in}


\textbf{Expectation Theory:} $i_{nt} = \frac{i_t+i^e_{t+1}+i^e_{t+2}+\dots+i^e_{t+(n-1)}}{n}$

\textbf{Liquidity Premium Theory:} $i_{nt} = \frac{i_t+i^e_{t+1}+i^e_{t+2}+\dots+i^e_{t+(n-1)}}{n}+l_{nt}$

$i_{nt}$:  interest rate on a n-year bond at year t (in \%);

$i_t$: interest rate on a 1-year bond at year t (in \%); 

$i^e_{t+1}$: interest rate on a 1-year bond expected for year t+1 at year t (in \%); 

$l_{nt}$: liquidity premium for the n-year bond at year t (in \%)



\vspace{1in}


\textbf{Monetary base}: MB=C+R 

\textbf{Monetary base}: MB=BR + $MB_n$

\textbf{M1}: M1=C+D

\textbf{currency-to-deposit ratio}: $c=\frac{C}{D}$

\textbf{excess reserves-deposit ratio}: $er=\frac{ER}{D}$

\textbf{required reserves ratio}: $rr=\frac{RR}{D}$

\textbf{reserves}: ${R=ER+RR}$

\textbf{Checkable deposits:} $D= \frac{1}{rr} \times R$

\textbf{Change in checkable deposits}: $\Delta D = \frac{1}{rr} \times \Delta R$

\textbf{money multiplier}: $m=\frac{1+c}{c+rr+er}$

\textbf{Money supply}: $M=m \times MB$

\textbf{Change in money supply}: $\Delta M=m \times \Delta MB$

$MB$: monetary base;   \hspace{4cm}  $C$: currency in circulation; 

$R$: reserves;  \hspace{5cm} $BR$: borrowed reserves; 

$MB_n$: non-borrowed monetary base;  \hspace{2cm} $D$: checkable deposits; 

$RR$: requires reserves;  \hspace{4cm} $ER$: excess reserves; 

$\Delta M$: change in M;  \hspace{4cm} $\Delta MB$: change in MB; 

$\Delta D$: change in D;  \hspace{4cm} $\Delta R$: change in R


\newpage

\textit{Work on this page will not be graded. You can detach this page.}