---
output: pdf_document
header-includes: 
  - \usepackage[utf8]{inputenc}
  - \usepackage{graphicx}
  - \usepackage{caption}
  - \usepackage[margin=1in]{geometry}
  - \usepackage{amsmath,amssymb}
  - \usepackage{multicol}
  - \usepackage{array}
  - \usepackage{tabulary}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newcommand{\class}{EC 313, Fall 2019}
\newcommand{\term}{Xiang LI (GE)}
\newcommand{\examnum}{Midterm 1 - Equation Sheet}

\noindent
\begin{tabular*}{\textwidth}{l @{\extracolsep{\fill}} r @{\extracolsep{6pt}} l}
\textbf{\class} & \textbf{Name: } & \makebox[2in]{\hrulefill}\\
\textbf{\term} &&\\
\textbf{\examnum} & \textbf{UO ID: } & \makebox[2in]{\hrulefill}\\
\end{tabular*}
\rule[2ex]{\textwidth}{2pt}

\textit{Work on this page will not be graded.}

growth rate of X at time t: $\frac{X_t-X_{t-1}}{X_{t-1}} \times 100\%$

GDP deflator: nominal GDP / real GDP

Future value: $FV_n=PV \times (1+i)^n$ 

Present value: $PV=\frac{FV_n}{(1+i)^n}$ 

Fixed-Payment Loan: Loan Value = $\frac{FP}{(1+i)}+ \frac{FP}{(1+i)^2} + \frac{FP}{(1+i)^3} + \ldots + \frac{FP}{(1+i)^n}$

Coupon Bond: Price = $\frac{C}{(1+i)}+ \frac{C}{(1+i)^2} + \frac{C}{(1+i)^3} + \ldots + \frac{C}{(1+i)^n} + \frac{F}{(1+i)^n}$

Coupon payment: $C=c \times F$

Discount Bond: Price = $\frac{F}{(1+i)^n}$

Holding Period Return:  $R=\frac{C+P_{t+1}-P_t}{P_t}=i_c+g$

Current Yield: $i_c=\frac{C}{P_t}$

Capital Gain: $g=\frac{P_{t+1}-P_t}{P_t}$

Fisher Equation: $i=r+\pi^{e}$

\vspace{.5in}


$PV$: present value (in $\$$);  \hspace{2cm}  $FV_n$: future value in n years (in $\$$); 

$n$: years to maturity;  \hspace{2.5cm}  $i$: (nominal) interest rate (in $\%$); 

$FP$: fixed payment (in $\$$); \hspace{2cm}  $C$: coupon payment (in $\$$); 

$c$: coupon rate (in $\%$); \hspace{2.5cm}  $F$: face value (in $\$$); 

$P_t$: price at year t (in $\$$); \hspace{2cm}  $P_{t+1}$: price at year t+1(in $\$$); 

$r$: real interest rate (in $\%$); \hspace{2cm} $\pi^e$: expected inflation (in $\%$).


\newpage

\textit{Work on this page will not be graded.}